version: "3"

services:
  nodered-cauldron:
    image: nodered-cauldron
    command: npm run dev
    container_name: nodered-cauldron
    build: nodered-cauldron
    volumes:
      - ./nodered-cauldron:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 1880:1880

  devices-iot-simulator:
    image: devices-iot-simulator
    command: npm run dev
    container_name: devices-iot-simulator
    build: devices-iot-simulator/server
    volumes:
      - ./devices-iot-simulator/server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      ENVIRONMENT: development
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001