version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: on-failure
    container_name: nginx
    volumes:
      - ./configs/.htpasswd:/etc/nginx/.htpasswd
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - nodered
      - nodered-cauldron
      - validation-web

  validation-web:
    image: nginx:alpine
    restart: on-failure
    container_name: validation-web
    volumes:
      - ./validation-web:/usr/share/nginx/html

  nodered:
    image: nodered/node-red:1.0.5
    container_name: nodered
    restart: on-failure

  nodered-cauldron:
    image: nodered-cauldron
    restart: on-failure
    command: npm run dev
    container_name: nodered-cauldron
    build: nodered-cauldron
    volumes:
      - ./nodered-cauldron:/usr/src/app
      - /usr/src/app/node_modules

  devices-iot-simulator:
    image: devices-iot-simulator
    restart: on-failure
    command: npm run dev
    container_name: devices-iot-simulator
    build: devices-iot-simulator/server
    volumes:
      - ./devices-iot-simulator/server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      ENVIRONMENT: development
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: on-failure
    container_name: mosquitto